#!/bin/bash
cd "$(dirname "$0")/.."
: ${PORT:=5000}
: ${RACK_ENV:=development}

cmd="bundle exec rackup -Ilib -s puma -p $PORT"
[[ "$RACK_ENV" == "development" ]] && exec rerun -p '**/*.{rb,ru}' "$cmd -o 127.0.0.1"
exec $cmd
